inherit_from: .rubocop_todo.yml

# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.4
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - context
  Exclude:
    - 'spec/unit/snapshot_spec.rb'

Layout/LineLength:
  Max: 120
  IgnoredPatterns:
    - !ruby/regexp /\A +(it|describe|context|shared_examples|include_examples|it_behaves_like) ["']/
